# Generated by Django 4.1.7 on 2023-09-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st',
            name='buyers',
        ),
    ]
