# Generated by Django 5.0.1 on 2024-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st',
            name='published',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Опубликовано'),
        ),
    ]
