# Generated by Django 4.1.7 on 2023-07-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_st_total_votes_st_votes_ratio_creview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='st',
            name='votes_ratio',
        ),
        migrations.DeleteModel(
            name='Creview',
        ),
    ]
