# Generated by Django 4.1.1 on 2022-10-14 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_publisher_alter_st_options_alter_st_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='st',
            name='buyers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Покупатели'),
        ),
    ]
