# Generated by Django 4.0.5 on 2022-09-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_genre_alter_st_content_alter_st_img_alter_st_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='st',
            options={'ordering': ['-published'], 'verbose_name': 'Игру', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterField(
            model_name='st',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='st',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='st',
            name='price',
            field=models.FloatField(blank=True, default='Free', null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='st',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.publisher', verbose_name='Издатель'),
        ),
    ]
